### ISSUE TITLE
The examples dds, envmap, theta360, tile, and video don't work

### ISSUE THREAD

**Issue by Erkaman** [mikolalysenko/regl#19]
When I load the example dds on http://regl.party , I just get a black black screen, and in the console it says

```

index.js:409XMLHttpRequest cannot load . Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.loadXHR @ index.js:409
index.js:409Uncaught TypeError: Cannot read property 'forEach' of undefinedloadXHR @ index.js:409
../../../../home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-pack/_prelude.js:1Not allowed to load local resource: blob:http%3A//regl.party/0902f0ef-e9db-452d-a3e9-07b055d25bf0
```

The same thing happens for all the examples dds, envmap, theta360, tile, and video. I can't run them locally on my machine either. I just get the same error.

**Comment by Erkaman** [comment]
The above was for Chrome. I also tried in Firefox, and it did not work there either.

**Comment by mikolalysenko** [comment]
Yeah, this is due to a hosting error with the assets not being mirrored properly on regl.party.  They work fine at the following URLs:

https://mikolalysenko.github.io/regl/www/gallery/dds.js.html
https://mikolalysenko.github.io/regl/www/gallery/video.js.html
https://mikolalysenko.github.io/regl/www/gallery/envmap.js.html
https://mikolalysenko.github.io/regl/www/gallery/theta360.js.html

**Comment by Erkaman** [comment]
Ok, I see.

**Comment by mikolalysenko** [comment]
The right place to fix this is probably on the site repo, https://github.com/freeman-lab/regl-site but issues there are turned off temporarily.
