### ISSUE TITLE
Getting canvas/context variables

### ISSUE THREAD

**Issue by dfcreative** [mikolalysenko/regl#4]
Hi!

Is there a simple way to get canvas element or context, created by regl instance? E. g. if I want to pass viewport size or canvas size to fragment shader. I skimmed through API / created objects and did not find any related properties.

One of the ways seems to be passing a function to uniform
```js
...
uniforms: {
	size: function (a,b,stats) {
		return [stats.width,stats.height];
	}
},
..
```
What are simpler ways for that? Creating and managing own canvas?

Thanks.

**Comment by mikolalysenko** [comment]
Nope!  If you want a handle to the canvas/context you need to pass them to regl yourself and maintain that reference.  This might change later, but at the moment I am writing this way as a challenge to try to design things so that you never have to dig down to that level.

Regarding that approach with the uniform, that is indeed the correct way to do it.  The reason for this is that the size of the WebGL context might change if you resize the window.

You can also access this information from outside a dynamic variable using `regl.stats`.

**Comment by dfcreative** [comment]
I see.
Well, for now it seems a bit more difficult than usual:
```js
draw({
size: [ctx.drawingBufferWidth, ctx.drawingBufferHeight]
});
```
But thanks anyways!

**Comment by mikolalysenko** [comment]
Ok, you can now do this in 0.6.0.  There is an unsafe escape hatch which allows you to grab the webgl context as `regl._gl`.  However a better way to get the drawing buffer height is to use the context variables.  For example:

```javascript
regl.frame((context) => {
  console.log(context.drawingBufferWidth, context.drawingBufferHeight)
})
```
