### ISSUE TITLE
WebGL types naming conventions

### ISSUE THREAD

**Issue by vorg** [mikolalysenko/regl#72]
Hi, I'm trying to port my PBR render from [pex](http://pex.gl) and I've found some inconsitiencies in how the WebGL enums are converted into strings:

UNSIGNED_SHORT = "uint8" why not "unsigned short"?
FLOAT = "float" why not "float32" then?
HALF_FLOAT = "half float" why not "float16" then?

DEPTH_STENCIL = "depth stencil"
DEPTH_COMPONENT = "depth" why not "depth component" then?

**Comment by mikolalysenko** [comment]
The rationale for `'uint8'` instead of unsigned short was that it is less stuff to type out.  That said, now you mention it maybe `'float32'` and `'float16'` are better names for the float channels.

I'm not super attached to the current conventions, though I'd like to keep everything succinct.  I'd be open to changing it before 1.0.0

**Comment by mikolalysenko** [comment]
I propose renaming `half float` to `float16` and adding an optional `float32` for specifying `float` and leaving `depth` and `depth stencil` as is.
